<?php

namespace Ihk\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * CookerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CookerRepository extends EntityRepository
{
}
