<?php

namespace Ihk\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * DishRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DishRepository extends EntityRepository
{
	public function findByKitchenId($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM IhkBaseBundle:Dish p where p.kitchenId ='.$id
			)
			->getResult();
	}

	public function findByTagId($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM IhkBaseBundle:Dish p JOIN p.tags t where t.id ='.$id
			)
			->getResult();
	}
}
