<?php

namespace Ihk\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * KitchenRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KitchenRepository extends EntityRepository
{
	public function findOneByOwnerId($id)
	{
		$query = $this->getEntityManager()
			->createQuery(
				'SELECT p FROM IhkBaseBundle:Kitchen p where p.ownerId =:id'
			)
			->setParameter('id', $id);

		try {
			return $query->getSingleResult();
		} catch (\Doctrine\ORM\NoResultException $e) {
			return null;
		}
	}
}
