<?php

namespace Ihk\BaseBundle\Entity;

use Doctrine\ORM\EntityRepository;

/**
 * RuleRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RuleRepository extends EntityRepository
{
	public function findByKitchenId($id)
	{
		return $this->getEntityManager()
			->createQuery(
				'SELECT p FROM IhkBaseBundle:Rule p where p.kitchenId ='.$id
			)
			->getResult();
	}
}
